syntax = "proto3";

package pb;

option go_package = "openhash/protobuf/pb";

enum Status {
  // zero value field required for proto3 compatibility
  UNUSED = 0;
  OK = 100;
  RESERVATION_REFUSED = 200;
  RESOURCE_LIMIT_EXCEEDED = 201;
  PERMISSION_DENIED = 202;
  CONNECTION_FAILED = 203;
  NO_RESERVATION = 204;
  MALFORMED_MESSAGE = 400;
  UNEXPECTED_MESSAGE = 401;
}

message Peer {
  bytes id = 1;
  repeated bytes addrs = 2;
}

message Reservation {
  uint64 expire = 1;  // Unix expiration time (UTC)
  repeated bytes addrs = 2;    // relay addrs for reserving peer
  bytes voucher = 3;  // reservation voucher
}

message Limit {
  uint32 duration = 1;  // seconds
  uint64 data = 2;      // bytes
}

message HopMessage {
  enum Type {
    RESERVE = 0;
    CONNECT = 1;
    STATUS = 2;
  }

  Type type = 1;
  Peer peer = 2;
  Reservation reservation = 3;
  Limit limit = 4;
  Status status = 5;
}

message StopMessage {
  enum Type {
    CONNECT = 0;
    STATUS = 1;
  }

  Type type = 1;
  Peer peer = 2;
  Limit limit = 3;
  Status status = 4;
}
