// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *UploadResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *UploadResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ContentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	IsDirectory   bool                   `protobuf:"varint,6,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RefCount      int32                  `protobuf:"varint,8,opt,name=ref_count,json=refCount,proto3" json:"ref_count,omitempty"`
	Chunks        []*ChunkInfo           `protobuf:"bytes,9,rep,name=chunks,proto3" json:"chunks,omitempty"`
	Links         []*Link                `protobuf:"bytes,10,rep,name=links,proto3" json:"links,omitempty"`
	Message       string                 `protobuf:"bytes,11,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentInfo) Reset() {
	*x = ContentInfo{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentInfo) ProtoMessage() {}

func (x *ContentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentInfo.ProtoReflect.Descriptor instead.
func (*ContentInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *ContentInfo) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ContentInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ContentInfo) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ContentInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ContentInfo) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

func (x *ContentInfo) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *ContentInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ContentInfo) GetRefCount() int32 {
	if x != nil {
		return x.RefCount
	}
	return 0
}

func (x *ContentInfo) GetChunks() []*ChunkInfo {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *ContentInfo) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ContentInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ContentInfoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Infos         []*ContentInfo         `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentInfoList) Reset() {
	*x = ContentInfoList{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentInfoList) ProtoMessage() {}

func (x *ContentInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentInfoList.ProtoReflect.Descriptor instead.
func (*ContentInfoList) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *ContentInfoList) GetInfos() []*ContentInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type StorageStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentCount  int64                  `protobuf:"varint,1,opt,name=content_count,json=contentCount,proto3" json:"content_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageStats) Reset() {
	*x = StorageStats{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageStats) ProtoMessage() {}

func (x *StorageStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageStats.ProtoReflect.Descriptor instead.
func (*StorageStats) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *StorageStats) GetContentCount() int64 {
	if x != nil {
		return x.ContentCount
	}
	return 0
}

type ReplicationStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReplicationFactor int32                  `protobuf:"varint,1,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	PinnedContent     int32                  `protobuf:"varint,2,opt,name=pinned_content,json=pinnedContent,proto3" json:"pinned_content,omitempty"`
	ReplicatingNow    int32                  `protobuf:"varint,3,opt,name=replicating_now,json=replicatingNow,proto3" json:"replicating_now,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReplicationStats) Reset() {
	*x = ReplicationStats{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationStats) ProtoMessage() {}

func (x *ReplicationStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationStats.ProtoReflect.Descriptor instead.
func (*ReplicationStats) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *ReplicationStats) GetReplicationFactor() int32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

func (x *ReplicationStats) GetPinnedContent() int32 {
	if x != nil {
		return x.PinnedContent
	}
	return 0
}

func (x *ReplicationStats) GetReplicatingNow() int32 {
	if x != nil {
		return x.ReplicatingNow
	}
	return 0
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Storage       *StorageStats          `protobuf:"bytes,1,opt,name=storage,proto3" json:"storage,omitempty"`
	Replication   *ReplicationStats      `protobuf:"bytes,2,opt,name=replication,proto3" json:"replication,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *StatsResponse) GetStorage() *StorageStats {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *StatsResponse) GetReplication() *ReplicationStats {
	if x != nil {
		return x.Replication
	}
	return nil
}

func (x *StatsResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type PinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinResponse) Reset() {
	*x = PinResponse{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinResponse) ProtoMessage() {}

func (x *PinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinResponse.ProtoReflect.Descriptor instead.
func (*PinResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *PinResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *PinResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PinListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        []string               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinListResponse) Reset() {
	*x = PinListResponse{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinListResponse) ProtoMessage() {}

func (x *PinListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinListResponse.ProtoReflect.Descriptor instead.
func (*PinListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *PinListResponse) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type PeerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Addresses     []string               `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerEvent) Reset() {
	*x = PeerEvent{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerEvent) ProtoMessage() {}

func (x *PeerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerEvent.ProtoReflect.Descriptor instead.
func (*PeerEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *PeerEvent) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PeerEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PeerEvent) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type DHTStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	PeerCount     int32                  `protobuf:"varint,2,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"` // bucket_info is complex, skipping for now
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DHTStats) Reset() {
	*x = DHTStats{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DHTStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DHTStats) ProtoMessage() {}

func (x *DHTStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DHTStats.ProtoReflect.Descriptor instead.
func (*DHTStats) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *DHTStats) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DHTStats) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

type NetworkStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PeerId         string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	ConnectedPeers int32                  `protobuf:"varint,2,opt,name=connected_peers,json=connectedPeers,proto3" json:"connected_peers,omitempty"`
	PeerList       []string               `protobuf:"bytes,3,rep,name=peer_list,json=peerList,proto3" json:"peer_list,omitempty"`
	Addresses      []string               `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Dht            *DHTStats              `protobuf:"bytes,5,opt,name=dht,proto3" json:"dht,omitempty"`
	PeerEvents     []*PeerEvent           `protobuf:"bytes,6,rep,name=peer_events,json=peerEvents,proto3" json:"peer_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkStatsResponse) Reset() {
	*x = NetworkStatsResponse{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStatsResponse) ProtoMessage() {}

func (x *NetworkStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStatsResponse.ProtoReflect.Descriptor instead.
func (*NetworkStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *NetworkStatsResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *NetworkStatsResponse) GetConnectedPeers() int32 {
	if x != nil {
		return x.ConnectedPeers
	}
	return 0
}

func (x *NetworkStatsResponse) GetPeerList() []string {
	if x != nil {
		return x.PeerList
	}
	return nil
}

func (x *NetworkStatsResponse) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *NetworkStatsResponse) GetDht() *DHTStats {
	if x != nil {
		return x.Dht
	}
	return nil
}

func (x *NetworkStatsResponse) GetPeerEvents() []*PeerEvent {
	if x != nil {
		return x.PeerEvents
	}
	return nil
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x06api.pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\n" +
	"core.proto\"n\n" +
	"\x0eUploadResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"S\n" +
	"\rErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x8b\x03\n" +
	"\vContentInfo\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x125\n" +
	"\bmod_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime\x12!\n" +
	"\fis_directory\x18\x06 \x01(\bR\visDirectory\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tref_count\x18\b \x01(\x05R\brefCount\x12*\n" +
	"\x06chunks\x18\t \x03(\v2\x12.core.pb.ChunkInfoR\x06chunks\x12#\n" +
	"\x05links\x18\n" +
	" \x03(\v2\r.core.pb.LinkR\x05links\x12\x18\n" +
	"\amessage\x18\v \x01(\tR\amessage\"<\n" +
	"\x0fContentInfoList\x12)\n" +
	"\x05infos\x18\x01 \x03(\v2\x13.api.pb.ContentInfoR\x05infos\"|\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"3\n" +
	"\fStorageStats\x12#\n" +
	"\rcontent_count\x18\x01 \x01(\x03R\fcontentCount\"\x91\x01\n" +
	"\x10ReplicationStats\x12-\n" +
	"\x12replication_factor\x18\x01 \x01(\x05R\x11replicationFactor\x12%\n" +
	"\x0epinned_content\x18\x02 \x01(\x05R\rpinnedContent\x12'\n" +
	"\x0freplicating_now\x18\x03 \x01(\x05R\x0ereplicatingNow\"\xb5\x01\n" +
	"\rStatsResponse\x12.\n" +
	"\astorage\x18\x01 \x01(\v2\x14.api.pb.StorageStatsR\astorage\x12:\n" +
	"\vreplication\x18\x02 \x01(\v2\x18.api.pb.ReplicationStatsR\vreplication\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\";\n" +
	"\vPinResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\")\n" +
	"\x0fPinListResponse\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\tR\x06hashes\"\x90\x01\n" +
	"\tPeerEvent\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\taddresses\x18\x04 \x03(\tR\taddresses\"C\n" +
	"\bDHTStats\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x02 \x01(\x05R\tpeerCount\"\xeb\x01\n" +
	"\x14NetworkStatsResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12'\n" +
	"\x0fconnected_peers\x18\x02 \x01(\x05R\x0econnectedPeers\x12\x1b\n" +
	"\tpeer_list\x18\x03 \x03(\tR\bpeerList\x12\x1c\n" +
	"\taddresses\x18\x04 \x03(\tR\taddresses\x12\"\n" +
	"\x03dht\x18\x05 \x01(\v2\x10.api.pb.DHTStatsR\x03dht\x122\n" +
	"\vpeer_events\x18\x06 \x03(\v2\x11.api.pb.PeerEventR\n" +
	"peerEventsB\x18Z\x16openhashdb/protobuf/pbb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_goTypes = []any{
	(*UploadResponse)(nil),        // 0: api.pb.UploadResponse
	(*ErrorResponse)(nil),         // 1: api.pb.ErrorResponse
	(*ContentInfo)(nil),           // 2: api.pb.ContentInfo
	(*ContentInfoList)(nil),       // 3: api.pb.ContentInfoList
	(*HealthResponse)(nil),        // 4: api.pb.HealthResponse
	(*StorageStats)(nil),          // 5: api.pb.StorageStats
	(*ReplicationStats)(nil),      // 6: api.pb.ReplicationStats
	(*StatsResponse)(nil),         // 7: api.pb.StatsResponse
	(*PinResponse)(nil),           // 8: api.pb.PinResponse
	(*PinListResponse)(nil),       // 9: api.pb.PinListResponse
	(*PeerEvent)(nil),             // 10: api.pb.PeerEvent
	(*DHTStats)(nil),              // 11: api.pb.DHTStats
	(*NetworkStatsResponse)(nil),  // 12: api.pb.NetworkStatsResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*ChunkInfo)(nil),             // 14: core.pb.ChunkInfo
	(*Link)(nil),                  // 15: core.pb.Link
}
var file_api_proto_depIdxs = []int32{
	13, // 0: api.pb.ContentInfo.mod_time:type_name -> google.protobuf.Timestamp
	13, // 1: api.pb.ContentInfo.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: api.pb.ContentInfo.chunks:type_name -> core.pb.ChunkInfo
	15, // 3: api.pb.ContentInfo.links:type_name -> core.pb.Link
	2,  // 4: api.pb.ContentInfoList.infos:type_name -> api.pb.ContentInfo
	13, // 5: api.pb.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 6: api.pb.StatsResponse.storage:type_name -> api.pb.StorageStats
	6,  // 7: api.pb.StatsResponse.replication:type_name -> api.pb.ReplicationStats
	13, // 8: api.pb.StatsResponse.timestamp:type_name -> google.protobuf.Timestamp
	13, // 9: api.pb.PeerEvent.timestamp:type_name -> google.protobuf.Timestamp
	11, // 10: api.pb.NetworkStatsResponse.dht:type_name -> api.pb.DHTStats
	10, // 11: api.pb.NetworkStatsResponse.peer_events:type_name -> api.pb.PeerEvent
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_core_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
