// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: protobuf/message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message_Wantlist_Entry_WantType int32

const (
	Message_Wantlist_Entry_Have  Message_Wantlist_Entry_WantType = 0
	Message_Wantlist_Entry_Block Message_Wantlist_Entry_WantType = 1
)

// Enum value maps for Message_Wantlist_Entry_WantType.
var (
	Message_Wantlist_Entry_WantType_name = map[int32]string{
		0: "Have",
		1: "Block",
	}
	Message_Wantlist_Entry_WantType_value = map[string]int32{
		"Have":  0,
		"Block": 1,
	}
)

func (x Message_Wantlist_Entry_WantType) Enum() *Message_Wantlist_Entry_WantType {
	p := new(Message_Wantlist_Entry_WantType)
	*p = x
	return p
}

func (x Message_Wantlist_Entry_WantType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Wantlist_Entry_WantType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_message_proto_enumTypes[0].Descriptor()
}

func (Message_Wantlist_Entry_WantType) Type() protoreflect.EnumType {
	return &file_protobuf_message_proto_enumTypes[0]
}

func (x Message_Wantlist_Entry_WantType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Wantlist_Entry_WantType.Descriptor instead.
func (Message_Wantlist_Entry_WantType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_message_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

type Message_BlockPresence_PresenceType int32

const (
	Message_BlockPresence_Have     Message_BlockPresence_PresenceType = 0
	Message_BlockPresence_DontHave Message_BlockPresence_PresenceType = 1
)

// Enum value maps for Message_BlockPresence_PresenceType.
var (
	Message_BlockPresence_PresenceType_name = map[int32]string{
		0: "Have",
		1: "DontHave",
	}
	Message_BlockPresence_PresenceType_value = map[string]int32{
		"Have":     0,
		"DontHave": 1,
	}
)

func (x Message_BlockPresence_PresenceType) Enum() *Message_BlockPresence_PresenceType {
	p := new(Message_BlockPresence_PresenceType)
	*p = x
	return p
}

func (x Message_BlockPresence_PresenceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_BlockPresence_PresenceType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_message_proto_enumTypes[1].Descriptor()
}

func (Message_BlockPresence_PresenceType) Type() protoreflect.EnumType {
	return &file_protobuf_message_proto_enumTypes[1]
}

func (x Message_BlockPresence_PresenceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_BlockPresence_PresenceType.Descriptor instead.
func (Message_BlockPresence_PresenceType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_message_proto_rawDescGZIP(), []int{0, 2, 0}
}

type Message struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Wantlist       *Message_Wantlist        `protobuf:"bytes,1,opt,name=wantlist,proto3" json:"wantlist,omitempty"`
	Blocks         []*Message_Block         `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	BlockPresences []*Message_BlockPresence `protobuf:"bytes,3,rep,name=block_presences,json=blockPresences,proto3" json:"block_presences,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_protobuf_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_protobuf_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetWantlist() *Message_Wantlist {
	if x != nil {
		return x.Wantlist
	}
	return nil
}

func (x *Message) GetBlocks() []*Message_Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *Message) GetBlockPresences() []*Message_BlockPresence {
	if x != nil {
		return x.BlockPresences
	}
	return nil
}

type Message_Wantlist struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Entries       []*Message_Wantlist_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Full          bool                      `protobuf:"varint,2,opt,name=full,proto3" json:"full,omitempty"` // If true, this is the full wantlist
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Wantlist) Reset() {
	*x = Message_Wantlist{}
	mi := &file_protobuf_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Wantlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Wantlist) ProtoMessage() {}

func (x *Message_Wantlist) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Wantlist.ProtoReflect.Descriptor instead.
func (*Message_Wantlist) Descriptor() ([]byte, []int) {
	return file_protobuf_message_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Message_Wantlist) GetEntries() []*Message_Wantlist_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Message_Wantlist) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

type Message_Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Block) Reset() {
	*x = Message_Block{}
	mi := &file_protobuf_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Block) ProtoMessage() {}

func (x *Message_Block) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Block.ProtoReflect.Descriptor instead.
func (*Message_Block) Descriptor() ([]byte, []int) {
	return file_protobuf_message_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Message_Block) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Message_Block) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Message_BlockPresence struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Hash          []byte                             `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Type          Message_BlockPresence_PresenceType `protobuf:"varint,2,opt,name=type,proto3,enum=bitswap.pb.Message_BlockPresence_PresenceType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_BlockPresence) Reset() {
	*x = Message_BlockPresence{}
	mi := &file_protobuf_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_BlockPresence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_BlockPresence) ProtoMessage() {}

func (x *Message_BlockPresence) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_BlockPresence.ProtoReflect.Descriptor instead.
func (*Message_BlockPresence) Descriptor() ([]byte, []int) {
	return file_protobuf_message_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Message_BlockPresence) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Message_BlockPresence) GetType() Message_BlockPresence_PresenceType {
	if x != nil {
		return x.Type
	}
	return Message_BlockPresence_Have
}

type Message_Wantlist_Entry struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Hash          []byte                          `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`                                                                          // The hash of the block
	Priority      int32                           `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`                                                                 // The priority of the want
	WantType      Message_Wantlist_Entry_WantType `protobuf:"varint,3,opt,name=want_type,json=wantType,proto3,enum=bitswap.pb.Message_Wantlist_Entry_WantType" json:"want_type,omitempty"` // Whether this is a want-have or want-block
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Wantlist_Entry) Reset() {
	*x = Message_Wantlist_Entry{}
	mi := &file_protobuf_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Wantlist_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Wantlist_Entry) ProtoMessage() {}

func (x *Message_Wantlist_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Wantlist_Entry.ProtoReflect.Descriptor instead.
func (*Message_Wantlist_Entry) Descriptor() ([]byte, []int) {
	return file_protobuf_message_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Message_Wantlist_Entry) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Message_Wantlist_Entry) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Message_Wantlist_Entry) GetWantType() Message_Wantlist_Entry_WantType {
	if x != nil {
		return x.WantType
	}
	return Message_Wantlist_Entry_Have
}

var File_protobuf_message_proto protoreflect.FileDescriptor

const file_protobuf_message_proto_rawDesc = "" +
	"\n" +
	"\x16protobuf/message.proto\x12\n" +
	"bitswap.pb\"\x89\x05\n" +
	"\aMessage\x128\n" +
	"\bwantlist\x18\x01 \x01(\v2\x1c.bitswap.pb.Message.WantlistR\bwantlist\x121\n" +
	"\x06blocks\x18\x02 \x03(\v2\x19.bitswap.pb.Message.BlockR\x06blocks\x12J\n" +
	"\x0fblock_presences\x18\x03 \x03(\v2!.bitswap.pb.Message.BlockPresenceR\x0eblockPresences\x1a\x81\x02\n" +
	"\bWantlist\x12<\n" +
	"\aentries\x18\x01 \x03(\v2\".bitswap.pb.Message.Wantlist.EntryR\aentries\x12\x12\n" +
	"\x04full\x18\x02 \x01(\bR\x04full\x1a\xa2\x01\n" +
	"\x05Entry\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12H\n" +
	"\twant_type\x18\x03 \x01(\x0e2+.bitswap.pb.Message.Wantlist.Entry.WantTypeR\bwantType\"\x1f\n" +
	"\bWantType\x12\b\n" +
	"\x04Have\x10\x00\x12\t\n" +
	"\x05Block\x10\x01\x1a/\n" +
	"\x05Block\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x1a\x8f\x01\n" +
	"\rBlockPresence\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12B\n" +
	"\x04type\x18\x02 \x01(\x0e2..bitswap.pb.Message.BlockPresence.PresenceTypeR\x04type\"&\n" +
	"\fPresenceType\x12\b\n" +
	"\x04Have\x10\x00\x12\f\n" +
	"\bDontHave\x10\x01B\x18Z\x16openhashdb/protobuf/pbb\x06proto3"

var (
	file_protobuf_message_proto_rawDescOnce sync.Once
	file_protobuf_message_proto_rawDescData []byte
)

func file_protobuf_message_proto_rawDescGZIP() []byte {
	file_protobuf_message_proto_rawDescOnce.Do(func() {
		file_protobuf_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_message_proto_rawDesc), len(file_protobuf_message_proto_rawDesc)))
	})
	return file_protobuf_message_proto_rawDescData
}

var file_protobuf_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protobuf_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protobuf_message_proto_goTypes = []any{
	(Message_Wantlist_Entry_WantType)(0),    // 0: bitswap.pb.Message.Wantlist.Entry.WantType
	(Message_BlockPresence_PresenceType)(0), // 1: bitswap.pb.Message.BlockPresence.PresenceType
	(*Message)(nil),                         // 2: bitswap.pb.Message
	(*Message_Wantlist)(nil),                // 3: bitswap.pb.Message.Wantlist
	(*Message_Block)(nil),                   // 4: bitswap.pb.Message.Block
	(*Message_BlockPresence)(nil),           // 5: bitswap.pb.Message.BlockPresence
	(*Message_Wantlist_Entry)(nil),          // 6: bitswap.pb.Message.Wantlist.Entry
}
var file_protobuf_message_proto_depIdxs = []int32{
	3, // 0: bitswap.pb.Message.wantlist:type_name -> bitswap.pb.Message.Wantlist
	4, // 1: bitswap.pb.Message.blocks:type_name -> bitswap.pb.Message.Block
	5, // 2: bitswap.pb.Message.block_presences:type_name -> bitswap.pb.Message.BlockPresence
	6, // 3: bitswap.pb.Message.Wantlist.entries:type_name -> bitswap.pb.Message.Wantlist.Entry
	1, // 4: bitswap.pb.Message.BlockPresence.type:type_name -> bitswap.pb.Message.BlockPresence.PresenceType
	0, // 5: bitswap.pb.Message.Wantlist.Entry.want_type:type_name -> bitswap.pb.Message.Wantlist.Entry.WantType
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_protobuf_message_proto_init() }
func file_protobuf_message_proto_init() {
	if File_protobuf_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_message_proto_rawDesc), len(file_protobuf_message_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_message_proto_goTypes,
		DependencyIndexes: file_protobuf_message_proto_depIdxs,
		EnumInfos:         file_protobuf_message_proto_enumTypes,
		MessageInfos:      file_protobuf_message_proto_msgTypes,
	}.Build()
	File_protobuf_message_proto = out.File
	file_protobuf_message_proto_goTypes = nil
	file_protobuf_message_proto_depIdxs = nil
}
