// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: message_v2.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tiered request that can carry preferences and priorities
type HierarchicalContentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hashes          []string               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	PreferDirect    bool                   `protobuf:"varint,2,opt,name=prefer_direct,json=preferDirect,proto3" json:"prefer_direct,omitempty"`
	AllowDelegation bool                   `protobuf:"varint,3,opt,name=allow_delegation,json=allowDelegation,proto3" json:"allow_delegation,omitempty"`
	AllowRelay      bool                   `protobuf:"varint,4,opt,name=allow_relay,json=allowRelay,proto3" json:"allow_relay,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HierarchicalContentRequest) Reset() {
	*x = HierarchicalContentRequest{}
	mi := &file_message_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HierarchicalContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HierarchicalContentRequest) ProtoMessage() {}

func (x *HierarchicalContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HierarchicalContentRequest.ProtoReflect.Descriptor instead.
func (*HierarchicalContentRequest) Descriptor() ([]byte, []int) {
	return file_message_v2_proto_rawDescGZIP(), []int{0}
}

func (x *HierarchicalContentRequest) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

func (x *HierarchicalContentRequest) GetPreferDirect() bool {
	if x != nil {
		return x.PreferDirect
	}
	return false
}

func (x *HierarchicalContentRequest) GetAllowDelegation() bool {
	if x != nil {
		return x.AllowDelegation
	}
	return false
}

func (x *HierarchicalContentRequest) GetAllowRelay() bool {
	if x != nil {
		return x.AllowRelay
	}
	return false
}

// Aggregated response status for multi-peer, multi-tier fetches
type MultiTierResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Blocks        []*MultiTierResponse_BlockStatus `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiTierResponse) Reset() {
	*x = MultiTierResponse{}
	mi := &file_message_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiTierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiTierResponse) ProtoMessage() {}

func (x *MultiTierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiTierResponse.ProtoReflect.Descriptor instead.
func (*MultiTierResponse) Descriptor() ([]byte, []int) {
	return file_message_v2_proto_rawDescGZIP(), []int{1}
}

func (x *MultiTierResponse) GetBlocks() []*MultiTierResponse_BlockStatus {
	if x != nil {
		return x.Blocks
	}
	return nil
}

// Delegated fetch coordination
type DelegatedFetchCoordination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AssignedPeers []string               `protobuf:"bytes,2,rep,name=assigned_peers,json=assignedPeers,proto3" json:"assigned_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegatedFetchCoordination) Reset() {
	*x = DelegatedFetchCoordination{}
	mi := &file_message_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegatedFetchCoordination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegatedFetchCoordination) ProtoMessage() {}

func (x *DelegatedFetchCoordination) ProtoReflect() protoreflect.Message {
	mi := &file_message_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegatedFetchCoordination.ProtoReflect.Descriptor instead.
func (*DelegatedFetchCoordination) Descriptor() ([]byte, []int) {
	return file_message_v2_proto_rawDescGZIP(), []int{2}
}

func (x *DelegatedFetchCoordination) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DelegatedFetchCoordination) GetAssignedPeers() []string {
	if x != nil {
		return x.AssignedPeers
	}
	return nil
}

// Relay routing and forwarding control
type RelayRouting struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CandidateRelays []string               `protobuf:"bytes,1,rep,name=candidate_relays,json=candidateRelays,proto3" json:"candidate_relays,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RelayRouting) Reset() {
	*x = RelayRouting{}
	mi := &file_message_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRouting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRouting) ProtoMessage() {}

func (x *RelayRouting) ProtoReflect() protoreflect.Message {
	mi := &file_message_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRouting.ProtoReflect.Descriptor instead.
func (*RelayRouting) Descriptor() ([]byte, []int) {
	return file_message_v2_proto_rawDescGZIP(), []int{3}
}

func (x *RelayRouting) GetCandidateRelays() []string {
	if x != nil {
		return x.CandidateRelays
	}
	return nil
}

// Generic error and status reporting for network operations
type OperationStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationStatus) Reset() {
	*x = OperationStatus{}
	mi := &file_message_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStatus) ProtoMessage() {}

func (x *OperationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_message_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationStatus.ProtoReflect.Descriptor instead.
func (*OperationStatus) Descriptor() ([]byte, []int) {
	return file_message_v2_proto_rawDescGZIP(), []int{4}
}

func (x *OperationStatus) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OperationStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MultiTierResponse_BlockStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`     // fetched, partial, missing, error
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"` // peer id
	Tier          uint32                 `protobuf:"varint,4,opt,name=tier,proto3" json:"tier,omitempty"`        // 1, 2, or 3
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiTierResponse_BlockStatus) Reset() {
	*x = MultiTierResponse_BlockStatus{}
	mi := &file_message_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiTierResponse_BlockStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiTierResponse_BlockStatus) ProtoMessage() {}

func (x *MultiTierResponse_BlockStatus) ProtoReflect() protoreflect.Message {
	mi := &file_message_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiTierResponse_BlockStatus.ProtoReflect.Descriptor instead.
func (*MultiTierResponse_BlockStatus) Descriptor() ([]byte, []int) {
	return file_message_v2_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MultiTierResponse_BlockStatus) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *MultiTierResponse_BlockStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MultiTierResponse_BlockStatus) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *MultiTierResponse_BlockStatus) GetTier() uint32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *MultiTierResponse_BlockStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_message_v2_proto protoreflect.FileDescriptor

var file_message_v2_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x76, 0x32, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x13, 0x6f, 0x70, 0x65, 0x6e, 0x68, 0x61, 0x73, 0x68, 0x2e, 0x62, 0x69, 0x74,
	0x73, 0x77, 0x61, 0x70, 0x2e, 0x76, 0x32, 0x22, 0xa5, 0x01, 0x0a, 0x1a, 0x48, 0x69, 0x65, 0x72,
	0x61, 0x72, 0x63, 0x68, 0x69, 0x63, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x12, 0x23,
	0x0a, 0x0d, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x64, 0x65, 0x6c,
	0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x61,
	0x6c, 0x6c, 0x6f, 0x77, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f,
	0x0a, 0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x22,
	0xe5, 0x01, 0x0a, 0x11, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x54, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x68, 0x61, 0x73, 0x68,
	0x2e, 0x62, 0x69, 0x74, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x76, 0x32, 0x2e, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x54, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x73, 0x1a, 0x83, 0x01, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x69, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x62, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x67,
	0x61, 0x74, 0x65, 0x64, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64,
	0x5f, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x50, 0x65, 0x65, 0x72, 0x73, 0x22, 0x39, 0x0a, 0x0c, 0x52,
	0x65, 0x6c, 0x61, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x29, 0x0a, 0x10, 0x63,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x6c, 0x61, 0x79, 0x73, 0x22, 0x3f, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x18, 0x5a, 0x16, 0x6f, 0x70, 0x65, 0x6e, 0x68,
	0x61, 0x73, 0x68, 0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_message_v2_proto_rawDescOnce sync.Once
	file_message_v2_proto_rawDescData []byte
)

func file_message_v2_proto_rawDescGZIP() []byte {
	file_message_v2_proto_rawDescOnce.Do(func() {
		file_message_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_v2_proto_rawDesc), len(file_message_v2_proto_rawDesc)))
	})
	return file_message_v2_proto_rawDescData
}

var file_message_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_message_v2_proto_goTypes = []any{
	(*HierarchicalContentRequest)(nil),    // 0: openhash.bitswap.v2.HierarchicalContentRequest
	(*MultiTierResponse)(nil),             // 1: openhash.bitswap.v2.MultiTierResponse
	(*DelegatedFetchCoordination)(nil),    // 2: openhash.bitswap.v2.DelegatedFetchCoordination
	(*RelayRouting)(nil),                  // 3: openhash.bitswap.v2.RelayRouting
	(*OperationStatus)(nil),               // 4: openhash.bitswap.v2.OperationStatus
	(*MultiTierResponse_BlockStatus)(nil), // 5: openhash.bitswap.v2.MultiTierResponse.BlockStatus
}
var file_message_v2_proto_depIdxs = []int32{
	5, // 0: openhash.bitswap.v2.MultiTierResponse.blocks:type_name -> openhash.bitswap.v2.MultiTierResponse.BlockStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_v2_proto_init() }
func file_message_v2_proto_init() {
	if File_message_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_v2_proto_rawDesc), len(file_message_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_v2_proto_goTypes,
		DependencyIndexes: file_message_v2_proto_depIdxs,
		MessageInfos:      file_message_v2_proto_msgTypes,
	}.Build()
	File_message_v2_proto = out.File
	file_message_v2_proto_goTypes = nil
	file_message_v2_proto_depIdxs = nil
}
