// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message_Wantlist_Entry_WantType int32

const (
	Message_Wantlist_Entry_Have  Message_Wantlist_Entry_WantType = 0
	Message_Wantlist_Entry_Block Message_Wantlist_Entry_WantType = 1
)

// Enum value maps for Message_Wantlist_Entry_WantType.
var (
	Message_Wantlist_Entry_WantType_name = map[int32]string{
		0: "Have",
		1: "Block",
	}
	Message_Wantlist_Entry_WantType_value = map[string]int32{
		"Have":  0,
		"Block": 1,
	}
)

func (x Message_Wantlist_Entry_WantType) Enum() *Message_Wantlist_Entry_WantType {
	p := new(Message_Wantlist_Entry_WantType)
	*p = x
	return p
}

func (x Message_Wantlist_Entry_WantType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Wantlist_Entry_WantType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (Message_Wantlist_Entry_WantType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x Message_Wantlist_Entry_WantType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Wantlist_Entry_WantType.Descriptor instead.
func (Message_Wantlist_Entry_WantType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

type Message_BlockPresence_PresenceType int32

const (
	Message_BlockPresence_Have     Message_BlockPresence_PresenceType = 0
	Message_BlockPresence_DontHave Message_BlockPresence_PresenceType = 1
)

// Enum value maps for Message_BlockPresence_PresenceType.
var (
	Message_BlockPresence_PresenceType_name = map[int32]string{
		0: "Have",
		1: "DontHave",
	}
	Message_BlockPresence_PresenceType_value = map[string]int32{
		"Have":     0,
		"DontHave": 1,
	}
)

func (x Message_BlockPresence_PresenceType) Enum() *Message_BlockPresence_PresenceType {
	p := new(Message_BlockPresence_PresenceType)
	*p = x
	return p
}

func (x Message_BlockPresence_PresenceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_BlockPresence_PresenceType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (Message_BlockPresence_PresenceType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x Message_BlockPresence_PresenceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_BlockPresence_PresenceType.Descriptor instead.
func (Message_BlockPresence_PresenceType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0, 2, 0}
}

type Message struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Wantlist       *Message_Wantlist        `protobuf:"bytes,1,opt,name=wantlist,proto3" json:"wantlist,omitempty"`
	Blocks         []*Message_Block         `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	BlockPresences []*Message_BlockPresence `protobuf:"bytes,3,rep,name=block_presences,json=blockPresences,proto3" json:"block_presences,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetWantlist() *Message_Wantlist {
	if x != nil {
		return x.Wantlist
	}
	return nil
}

func (x *Message) GetBlocks() []*Message_Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *Message) GetBlockPresences() []*Message_BlockPresence {
	if x != nil {
		return x.BlockPresences
	}
	return nil
}

type Message_Wantlist struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Entries       []*Message_Wantlist_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Full          bool                      `protobuf:"varint,2,opt,name=full,proto3" json:"full,omitempty"` // If true, this is the full wantlist
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Wantlist) Reset() {
	*x = Message_Wantlist{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Wantlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Wantlist) ProtoMessage() {}

func (x *Message_Wantlist) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Wantlist.ProtoReflect.Descriptor instead.
func (*Message_Wantlist) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Message_Wantlist) GetEntries() []*Message_Wantlist_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Message_Wantlist) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

type Message_Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Block) Reset() {
	*x = Message_Block{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Block) ProtoMessage() {}

func (x *Message_Block) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Block.ProtoReflect.Descriptor instead.
func (*Message_Block) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Message_Block) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Message_Block) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Message_BlockPresence struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Hash          []byte                             `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Type          Message_BlockPresence_PresenceType `protobuf:"varint,2,opt,name=type,proto3,enum=bitswap.pb.Message_BlockPresence_PresenceType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_BlockPresence) Reset() {
	*x = Message_BlockPresence{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_BlockPresence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_BlockPresence) ProtoMessage() {}

func (x *Message_BlockPresence) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_BlockPresence.ProtoReflect.Descriptor instead.
func (*Message_BlockPresence) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Message_BlockPresence) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Message_BlockPresence) GetType() Message_BlockPresence_PresenceType {
	if x != nil {
		return x.Type
	}
	return Message_BlockPresence_Have
}

type Message_Wantlist_Entry struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Hash          []byte                          `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`                                                                          // The hash of the block
	Priority      int32                           `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`                                                                 // The priority of the want
	WantType      Message_Wantlist_Entry_WantType `protobuf:"varint,3,opt,name=want_type,json=wantType,proto3,enum=bitswap.pb.Message_Wantlist_Entry_WantType" json:"want_type,omitempty"` // Whether this is a want-have or want-block
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Wantlist_Entry) Reset() {
	*x = Message_Wantlist_Entry{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Wantlist_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Wantlist_Entry) ProtoMessage() {}

func (x *Message_Wantlist_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Wantlist_Entry.ProtoReflect.Descriptor instead.
func (*Message_Wantlist_Entry) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Message_Wantlist_Entry) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *Message_Wantlist_Entry) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Message_Wantlist_Entry) GetWantType() Message_Wantlist_Entry_WantType {
	if x != nil {
		return x.WantType
	}
	return Message_Wantlist_Entry_Have
}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = string([]byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x62, 0x69, 0x74, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x70, 0x62, 0x22, 0x89, 0x05, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x77, 0x61, 0x6e, 0x74, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x69, 0x74, 0x73,
	0x77, 0x61, 0x70, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x57,
	0x61, 0x6e, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x08, 0x77, 0x61, 0x6e, 0x74, 0x6c, 0x69, 0x73,
	0x74, 0x12, 0x31, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x62, 0x69, 0x74, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x70, 0x62, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x12, 0x4a, 0x0a, 0x0f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x72,
	0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x62, 0x69, 0x74, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65,
	0x52, 0x0e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x73,
	0x1a, 0x81, 0x02, 0x0a, 0x08, 0x57, 0x61, 0x6e, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x3c, 0x0a,
	0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x62, 0x69, 0x74, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x57, 0x61, 0x6e, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x75, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x66, 0x75, 0x6c, 0x6c, 0x1a,
	0xa2, 0x01, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x48, 0x0a, 0x09, 0x77, 0x61, 0x6e,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x62,
	0x69, 0x74, 0x73, 0x77, 0x61, 0x70, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x57, 0x61, 0x6e, 0x74, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x2e, 0x57, 0x61, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x77, 0x61, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x1f, 0x0a, 0x08, 0x57, 0x61, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x08, 0x0a, 0x04, 0x48, 0x61, 0x76, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x10, 0x01, 0x1a, 0x2f, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x8f, 0x01, 0x0a, 0x0d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50,
	0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x42, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e, 0x2e, 0x62, 0x69, 0x74, 0x73,
	0x77, 0x61, 0x70, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x65,
	0x73, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22,
	0x26, 0x0a, 0x0c, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x08, 0x0a, 0x04, 0x48, 0x61, 0x76, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x6f, 0x6e,
	0x74, 0x48, 0x61, 0x76, 0x65, 0x10, 0x01, 0x42, 0x18, 0x5a, 0x16, 0x6f, 0x70, 0x65, 0x6e, 0x68,
	0x61, 0x73, 0x68, 0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_message_proto_goTypes = []any{
	(Message_Wantlist_Entry_WantType)(0),    // 0: bitswap.pb.Message.Wantlist.Entry.WantType
	(Message_BlockPresence_PresenceType)(0), // 1: bitswap.pb.Message.BlockPresence.PresenceType
	(*Message)(nil),                         // 2: bitswap.pb.Message
	(*Message_Wantlist)(nil),                // 3: bitswap.pb.Message.Wantlist
	(*Message_Block)(nil),                   // 4: bitswap.pb.Message.Block
	(*Message_BlockPresence)(nil),           // 5: bitswap.pb.Message.BlockPresence
	(*Message_Wantlist_Entry)(nil),          // 6: bitswap.pb.Message.Wantlist.Entry
}
var file_message_proto_depIdxs = []int32{
	3, // 0: bitswap.pb.Message.wantlist:type_name -> bitswap.pb.Message.Wantlist
	4, // 1: bitswap.pb.Message.blocks:type_name -> bitswap.pb.Message.Block
	5, // 2: bitswap.pb.Message.block_presences:type_name -> bitswap.pb.Message.BlockPresence
	6, // 3: bitswap.pb.Message.Wantlist.entries:type_name -> bitswap.pb.Message.Wantlist.Entry
	1, // 4: bitswap.pb.Message.BlockPresence.type:type_name -> bitswap.pb.Message.BlockPresence.PresenceType
	0, // 5: bitswap.pb.Message.Wantlist.Entry.want_type:type_name -> bitswap.pb.Message.Wantlist.Entry.WantType
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
